name: Build and Package Extension

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build for Chrome
      run: npm run build -- --env browser=chrome

    - name: Package Chrome extension
      run: |
        mkdir -p release
        cd dist
        zip -r ../release/chrome-extension.zip .

    - name: Build for Firefox
      run: npm run build -- --env browser=firefox

    - name: Package Firefox extension
      run: |
        cd dist
        zip -r ../release/firefox-extension.zip .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extensions
        path: release/